Revert "nushell: update to 0.22.0"
This reverts commit ded543e0e6805f02c19269e65febeeb22fe864b3.

error[E0658]: use of unstable library feature 'tau_constant'